# Fedora docker image.
image: fedora:27

services:
  - docker:dind

build:
  stage: build
  artifacts:
    paths:
    - john.flatpak

  variables:
    BUNDLE: "john.flatpak"
    
  script:
    - env
    - dnf -y update
    - dnf install -y flatpak flatpak-builder elfutils
    - flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
    - flatpak install -y gnome org.freedesktop.Platform//1.6 org.freedesktop.Sdk//1.6

    # Build and export the flatpak package
    - cd john-the-ripper/flatpak
    - flatpak-builder --repo=repo build com.openwall.John.json
    - flatpak build-bundle repo john.flatpak com.openwall.John
    - cp john.flatpak "$CI_PROJECT_DIR"

  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://gitlab.com/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/${BUNDLE}

deploy:
  stage: deploy

  script:
    # Set up
    - dnf -y update
    - dnf install -y flatpak ostree
    - flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
    - flatpak install -y gnome org.freedesktop.Platform//1.6
    - echo Flatpak Installed

    # Install flatpak package
    - ostree --repo=repo init --mode=archive-z2
    - flatpak build-import-bundle repo john.flatpak
    - flatpak --user remote-add --no-gpg-verify --if-not-exists tutorial-repo repo
    - flatpak --user install -y tutorial-repo com.openwall.John

    # Do some testing
    - flatpak run com.openwall.John
    - flatpak run com.openwall.John --list=build-info
    - flatpak run com.openwall.John --test-full=0 --format=sha512crypt
