# Fedora docker image.
image: fedora:latest

services:
  - docker:dind

build:
  stage: build
  artifacts:
    paths:
    - john.flatpak

  variables:
    BUNDLE: "john.flatpak"
    
  script:
    - env
    - dnf -y update
    - dnf install -y flatpak flatpak-builder elfutils
    - flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
    - flatpak install -y gnome org.freedesktop.Platform//1.6 org.freedesktop.Sdk//1.6

    # Build and export the flatpak package
    - cd john-the-ripper/flatpak
    - flatpak-builder --repo=repo build com.openwall.John.json
    - flatpak build-bundle repo john.flatpak com.openwall.John
    - cp john.flatpak "$CI_PROJECT_DIR"

  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://gitlab.com/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/raw/${BUNDLE}

deploy:
  stage: deploy

  script:
    # Set up
    - dnf -y update
    - dnf install -y flatpak ostree
    - flatpak remote-add --from gnome https://sdk.gnome.org/gnome.flatpakrepo
    - flatpak install -y gnome org.freedesktop.Platform//1.6
    - echo Flatpak Installed

    # Install flatpak package
    - ostree --repo=repo init --mode=archive-z2
    - flatpak build-import-bundle repo john.flatpak
    - flatpak --user remote-add --no-gpg-verify --if-not-exists tutorial-repo repo
    - flatpak --user install -y tutorial-repo com.openwall.John

    # Do some testing
    - flatpak run com.openwall.John
    - flatpak run com.openwall.John --list=build-info
    - export JTR_BIN='flatpak run com.openwall.John'

    - echo '$NT$066ddfd4ef0e9cd7c256fe77191ef43c' > ~/tests.in
    - echo '$NT$8846f7eaee8fb117ad06bdd830b7586c' >> ~/tests.in
    - echo 'df64225ca3472d32342dd1a33e4d7019f01c513ed7ebe85c6af102f6473702d2' >> ~/tests.in
    - echo '73e6bc8a66b5cead5e333766963b5744c806d1509e9ab3a31b057a418de5c86f' >> ~/tests.in
    - echo '$6$saltstring$fgNTR89zXnDUV97U5dkWayBBRaB0WIBnu6s4T7T8Tz1SbUyewwiHjho25yWVkph2p18CmUkqXh4aIyjPnxdgl0' >> ~/tests.in

    - echo
    - echo "====> T4:"
    - $JTR_BIN -test-full=0 --format=nt
    - echo "====> T5:"
    - $JTR_BIN -test-full=0 --format=sha256crypt
    - echo "------------------------------------------------------------------"
    - $JTR_BIN -test=0 --format=raw*
    - echo "------------------------------------------------------------------"

    - echo "====> T10:"
    - $JTR_BIN ~/tests.in --format=nt --fork=2
    - echo "====> T11:"
    - $JTR_BIN ~/tests.in --format=raw-sha256 --fork=2
    - echo "====> T12-a:"
    - $JTR_BIN ~/tests.in --format=sha512crypt --mask=jo?l[n-q]
